### ISSUE TITLE
File Descriptor 

### ISSUE THREAD

**Issue by kelvinquan** [ros-drivers/libuvc_ros#55]
Hi, 

I am currently using libuvc for my camera. I would like to use the ioctl function to set the triggering mode for this camera and it requires the file descriptor to the open device. Unlike open() which returns the file descriptor of the open device, uvc_open() returns the handle to the open device. As such, I am unable to use the ioctl function to set the triggering mode.

Would appreciate for an advice on the above-mentioned issue.

Thanks

Regards
Kelvin

**Comment by 7675t** [comment]
If your camera support UVC, I think usually you don't need to use raw API like ioctrl() to change something on the camera. You may be able to control via higher level API, say UVC's extension. Are you sure you need to use ioctl?

**Comment by kelvinquan** [comment]
Hi, Mau 

> If your camera support UVC, I think usually you don't need to use raw API like ioctrl() to change something on the camera. You may be able to control via higher level API, say UVC's extension. Are you sure you need to use ioctl?

Yup I need to use ioctl for my application. Do you have any ideas how can I obtained file descriptor integer using libuvc_open? libuvc_opene return a handles of the device, which ioctl does not accept as an input parameter.

Thanks

Regards
Kelvin

**Comment by 7675t** [comment]
And this repository is on the ROS package, so you may get helped better in libuvc repository.

**Comment by kelvinquan** [comment]
> And this repository is on the ROS package, so you may get helped better in libuvc repository.

Cheers! Thanks :)
