### ISSUE TITLE
Makefile:140: recipe for target 'all' failed make: *** [all] Error 2 Invoking "make -j12 -l12" failed

### ISSUE THREAD

**Issue by xiejingjacob** [ros-drivers/libuvc_ros#64]
I just git clone the packages and catkin_make, I got such error.

My ROS verision is kinetic

CMakeFiles/camera_node.dir/src/camera_driver.cpp.o: In function `libuvc_camera::CameraDriver::~CameraDriver()':
camera_driver.cpp:(.text+0x4a4): undefined reference to `uvc_free_frame'
camera_driver.cpp:(.text+0x4c7): undefined reference to `uvc_exit'
CMakeFiles/camera_node.dir/src/camera_driver.cpp.o: In function `libuvc_camera::CameraDriver::Start()':
camera_driver.cpp:(.text+0x67f): undefined reference to `uvc_init'
camera_driver.cpp:(.text+0x6a0): undefined reference to `uvc_perror'
CMakeFiles/camera_node.dir/src/camera_driver.cpp.o: In function `libuvc_camera::CameraDriver::Stop()':
camera_driver.cpp:(.text+0x847): undefined reference to `uvc_exit'
CMakeFiles/camera_node.dir/src/camera_driver.cpp.o: In function `libuvc_camera::CameraDriver::ReconfigureCallback(libuvc_camera::UVCCameraConfig&, unsigned int)':
camera_driver.cpp:(.text+0xa0d): undefined reference to `uvc_set_scanning_mode'
camera_driver.cpp:(.text+0xba5): undefined reference to `uvc_set_ae_mode'
camera_driver.cpp:(.text+0xd32): undefined reference to `uvc_set_ae_priority'
camera_driver.cpp:(.text+0xeda): undefined reference to `uvc_set_exposure_abs'
camera_driver.cpp:(.text+0x107e): undefined reference to `uvc_set_focus_auto'
camera_driver.cpp:(.text+0x120c): undefined reference to `uvc_set_focus_abs'
camera_driver.cpp:(.text+0x1399): undefined reference to `uvc_set_gain'
camera_driver.cpp:(.text+0x1538): undefined reference to `uvc_set_iris_abs'
camera_driver.cpp:(.text+0x16c0): undefined reference to `uvc_set_brightness'
camera_driver.cpp:(.text+0x1860): undefined reference to `uvc_set_pantilt_abs'
CMakeFiles/camera_node.dir/src/camera_driver.cpp.o: In function `libuvc_camera::CameraDriver::ImageCallback(uvc_frame*)':
camera_driver.cpp:(.text+0x1ee0): undefined reference to `uvc_uyvy2bgr'
camera_driver.cpp:(.text+0x1f01): undefined reference to `uvc_perror'
camera_driver.cpp:(.text+0x2192): undefined reference to `uvc_yuyv2bgr'
camera_driver.cpp:(.text+0x21b3): undefined reference to `uvc_perror'
camera_driver.cpp:(.text+0x2266): undefined reference to `uvc_mjpeg2rgb'
camera_driver.cpp:(.text+0x2287): undefined reference to `uvc_perror'
camera_driver.cpp:(.text+0x2327): undefined reference to `uvc_any2bgr'
camera_driver.cpp:(.text+0x2348): undefined reference to `uvc_perror'
CMakeFiles/camera_node.dir/src/camera_driver.cpp.o: In function `libuvc_camera::CameraDriver::OpenCamera(libuvc_camera::UVCCameraConfig&)':
camera_driver.cpp:(.text+0x301c): undefined reference to `uvc_find_devices'
camera_driver.cpp:(.text+0x303d): undefined reference to `uvc_perror'
camera_driver.cpp:(.text+0x30de): undefined reference to `uvc_unref_device'
camera_driver.cpp:(.text+0x3236): undefined reference to `uvc_open'
camera_driver.cpp:(.text+0x3330): undefined reference to `uvc_get_device_address'
camera_driver.cpp:(.text+0x3349): undefined reference to `uvc_get_bus_number'
camera_driver.cpp:(.text+0x345f): undefined reference to `uvc_strerror'
camera_driver.cpp:(.text+0x3478): undefined reference to `uvc_get_device_address'
camera_driver.cpp:(.text+0x3491): undefined reference to `uvc_get_bus_number'
camera_driver.cpp:(.text+0x34f8): undefined reference to `uvc_unref_device'
camera_driver.cpp:(.text+0x351f): undefined reference to `uvc_set_status_callback'
camera_driver.cpp:(.text+0x35a5): undefined reference to `uvc_get_stream_ctrl_format_size'
camera_driver.cpp:(.text+0x35d6): undefined reference to `uvc_perror'
camera_driver.cpp:(.text+0x35ec): undefined reference to `uvc_close'
camera_driver.cpp:(.text+0x3602): undefined reference to `uvc_unref_device'
camera_driver.cpp:(.text+0x3721): undefined reference to `uvc_print_diag'
camera_driver.cpp:(.text+0x3755): undefined reference to `uvc_start_streaming'
camera_driver.cpp:(.text+0x3776): undefined reference to `uvc_perror'
camera_driver.cpp:(.text+0x378c): undefined reference to `uvc_close'
camera_driver.cpp:(.text+0x37a2): undefined reference to `uvc_unref_device'
camera_driver.cpp:(.text+0x37d0): undefined reference to `uvc_free_frame'
camera_driver.cpp:(.text+0x37fd): undefined reference to `uvc_allocate_frame'
CMakeFiles/camera_node.dir/src/camera_driver.cpp.o: In function `libuvc_camera::CameraDriver::CloseCamera()':
camera_driver.cpp:(.text+0x39ab): undefined reference to `uvc_close'
camera_driver.cpp:(.text+0x39cd): undefined reference to `uvc_unref_device'
collect2: error: ld returned 1 exit status
libuvc_ros/libuvc_camera/CMakeFiles/camera_node.dir/build.make:192: recipe for target '/home/ur5/ur5_ws/devel/lib/libuvc_camera/camera_node' failed
make[2]: *** [/home/ur5/ur5_ws/devel/lib/libuvc_camera/camera_node] Error 1
CMakeFiles/Makefile2:8705: recipe for target 'libuvc_ros/libuvc_camera/CMakeFiles/camera_node.dir/all' failed
make[1]: *** [libuvc_ros/libuvc_camera/CMakeFiles/camera_node.dir/all] Error 2

Could you tell me how to fix such error?

**Comment by mengfanli** [comment]
I got the same problem, i had install libuvc form 'https://github.com/libuvc/libuvc', have you solved it?

**Comment by xiejingjacob** [comment]
> I got the same problem, i had install libuvc form 'https://github.com/libuvc/libuvc', have you solved it?

I have installed the ROS package by sudo apt-get install ros-kinetic-libuvc-camera.

**Comment by mengfanli** [comment]
> > I got the same problem, i had install libuvc form 'https://github.com/libuvc/libuvc', have you solved it?
> 
> I have installed the ROS package by sudo apt-get install ros-kinetic-libuvc-camera, which does not meet the problem above

yes, great! I removed those libs from "libuvc" and installed ros-kinetic-libuvc-camera,  catkin_make works. thanks~
