### ISSUE TITLE
Release on noetic

### ISSUE THREAD

**Issue by vincentrou** [ros-drivers/libuvc_ros#69]
Is it possible to release this package on noetic ? It works fine on Ubuntu 20.04 with libuvc-dev (PR in rosdep https://github.com/ros/rosdistro/pull/28285)

I can help to release it if needed.

**Comment by vincentrou** [comment]
libuvc-dev has been merged in rosdistro.
I am willing to help the maintenance of this package. @ktossell @k-okada

**Comment by k-okada** [comment]
@vincentrou sorry for late. To release libuvc_ros, we need to release `libuvc` first.
I'll release `libuvc_ros` once https://github.com/ros/rosdistro/pull/28353 is merged.

**Comment by vincentrou** [comment]
@k-okada We do not need to release libuvc on rosdistro as a ros pkg since it is already released as a deb pkg on [ubuntu](https://packages.ubuntu.com/focal/libuvc-dev) and debian. This is why I ask for this PR ros/rosdistro#28285.

We just need to change the package.xml dependecy from libuvc to libuvc-dev. Right ?

**Comment by k-okada** [comment]
@vincentrou oh, I understand, released with system `libuvc` pkg https://github.com/ros/rosdistro/pull/28364

Note that we do not have libuvc for fedra, so skipped releasing them. If you find libuvc-dev for fedra, please add them to ros/rosdistro.
```
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/09a719f446d95d0805add1f012509f/index-v4.yaml'
Could not resolve rosdep key 'libuvc-dev' for distro '32':
No definition of [libuvc-dev] for OS [fedora]
        rosdep key : libuvc-dev
        OS name    : fedora
        OS version : 32
        Data:
debian:
                  '*':
                  - libuvc-dev
                  stretch: null
                gentoo:
                - media-libs/libuvc
                ubuntu:
                  '*':
                  - libuvc-dev
                  xenial: null

Failed to resolve libuvc-dev on fedora:32 with: Error running generator: Failed to resolve rosdep key 'libuvc-dev', aborting.
libuvc-dev is depended on by these packages: ['libuvc_camera']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
<== The following generator action reported that it is missing one or more
    rosdep keys, but that the key exists in other platforms:
'['/usr/bin/git-bloom-generate', '-y', 'rosrpm', '--prefix', 'release/noetic', 'noetic', '-i', '1', '--os-name', 'fedora']'
```

**Comment by vincentrou** [comment]
Thanks for the release
